data:
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 1
crosscoder:
  n_latents: 8192
train:
  num_steps: 100
  batch_size: 32
  log_every_n_steps: 10
  final_lambda_s: 5
  lambda_s_num__steps: 1000
experiment_name: l1_crosscoder_example
hookpoints: [
  "blocks.4.hook_resid_post"
  "blocks.8.hook_resid_post"
]